apiVersion: v1
kind: Service
metadata:
  name: app1
  labels:
    app: app1
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  - port: 8080
    targetPort: http  
    protocol: TCP     
    name: http2
  selector:
    app: app1