apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps-dev
  
  source:
    repoURL: https://github.com/solas98/kustomize-demo.git
    targetRevision: main
    path: apps/app1/overlays/dev
  
  destination:
    server: https://kubernetes.default.svc
    namespace: app1-dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m